# Generated by Django 4.1 on 2022-10-20 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('emp_id', models.IntegerField()),
                ('position', models.CharField(choices=[('worker', 'worker'), ('superwiser', 'superwiser'), ('production_manager', 'production_manager'), ('qwality_head', 'qwality_head'), ('plant_head', 'plant_head'), ('Director', 'Director')], default='worker', max_length=50)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('mobile', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
